version: '3.8'

services:
  mail:
    image: rnwood/smtp4dev:3.1.3-ci20211206101
    ports:
      - '8888:80'
      - '25:25'
      - '143:143'
    volumes:
      - ./data/smtp4dev:/smtp4dev

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: serverist
      MYSQL_USER: develop
      MYSQL_PASSWORD: develop
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql