= Serverist

Kotlin + DDD × クリーンアーキテクチャで作るマイクラ用のサーバーリスト

参考: https://minecraft.jp

== ディレクトリ構成

=== `/application`

アプリケーション層

クライアントサイドとサーバーサイドのインターフェースが定義されている。

=== `/domain`

ドメイン層

サーバーサイドのみ利用

=== `/backend`

サーバーサイド

Ktor + GraphQL + Exposedで構成。

=== `/clientCommon`

クライアントサイドのアプリケーション層の実装や、Jetpack Composeのコンポーネント(UI)が含まれる。

View層はInteractor等の実装に依存してはイケナイため、おそらくUIは別のサブプロジェクトで記述した方が管理がしやすい。

=== `/webCompose`

Kotlin/JSとJetpack Compose for Webで作るSPAプロジェクト。
``compose.material``がfor Webに対応するまでは、``/clientCommon``とは別にこのプロジェクト内で全てのコンポーネントを作成する必要がある。

=== `/webReact`

Kotlin/JSとReactで作るSPAプロジェクト

== 知見

=== Clean Architecture

==== サーバーサイドとクライアントサイドでUseCaseの共通化は難しい

. サーバーサイドでは全てのユーザーに対してUseCaseが使われるため、IDによってUseCaseがユーザーを識別する必要がある。 クライアントサイドではCookieなどを使って誰であるかを表現するため、UseCaseでIDを使うべきではない。 つまり、UseCaseの引数の統一が困難である。
. また、サーバーサイドとクライアントサイドで必要となるUseCaseやUseCaseのパッケージの場所(CQRSを適用している場合)が異なる。

NOTE: 本プロジェクトでは、``:application``サブプロジェクトでサーバーサイドとクライアントサイドのアプリケーション層のコードを管理している。そこではUseCase本体の共通化はしていないものの、Entityは共通化しているためある程度の冗長性の削減は達成できている。それらのEntityはGraphQLを介して共有されるため、スキーマの管理さえ徹底していれば型の安全は保証される。

==== UseCaseの引数にはDTOを使うべき

https://qiita.com/UramnOIL/items/94daff83e1dc85283882