= Serverist

Kotlin + DDD × クリーンアーキテクチャで作るマイクラ用のサーバーリスト

参考: https://minecraft.jp

== ディレクトリ構成

=== `/application`

アプリケーション層

クライアントサイドとサーバーサイドのインターフェースが定義されている。

=== `/domain`

ドメイン層

サーバーサイドのみ利用

=== `/backend`

サーバーサイド

Ktor + GraphQL + Exposedで構成。

=== `/clientCommon`

クライアントサイドのアプリケーション層の実装や、Jetpack Composeのコンポーネント(UI)が含まれる。

View層はInteractor等の実装に依存してはイケナイため、おそらくUIは別のサブプロジェクトで記述した方が管理がしやすい。

=== `/web`

Kotlin/JSとJetpack Compose for Webで作るSPAプロジェクト。
``compose.material``がfor Webに対応するまでは、``/clientCommon``とは別にこのプロジェクト内で全てのコンポーネントを作成する必要がある。

== 知見

=== Clean Architecture

==== サーバーサイドとクライアントサイドでUseCaseの共通化は難しい

. サーバーサイドでは全てのユーザーに対してUseCaseが使われるため、IDによってUseCaseがユーザーを識別する必要がある。 クライアントサイドではCookieなどを使って誰であるかを表現するため、UseCaseでIDを使うべきではない。 つまり、UseCaseの引数の統一が困難である。
. また、サーバーサイドとクライアントサイドで必要となるUseCaseやUseCaseのパッケージの場所(CQRSを適用している場合)が異なる。

NOTE: Kotlin Multiplatform Projectの場合、``actual``キーワードを使って引数の設定を先延ばしにできるが、Gradleでサーバーとクライアントのそれぞれでターゲットを変えることが困難であるため現実的ではない。試しにソースセットに``client``と``server``を追加してみたが、ボトムのソースセットに適用しないと注意され、また、別プロジェクトから依存させても追加したソースセットを参照できないため、``actual``キーワードを使った管理方法は断念した。

==== UseCaseの引数にはDTOを使うべき

https://qiita.com/UramnOIL/items/94daff83e1dc85283882