name: 'Deploy Document to GitHub Pages'

on:
  push:
    branches:
      - master
    paths:
      - '**/src/**'
  pull_request:

jobs:
  build:
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v2

      - name: Build Dokka
        run: ./gradlew dokkaHtmlMultiModule

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokkaHtmlMultiModule